# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lightrains Technolabs
email: hexlxlo@xligxhtrxaxixnxs.com
pgp: B376 B0A4 07CF 4EB7 5B38  DCB0 6D2A DCDD C146 A5BE
slogan: Technology Supercharged
masthead: Engineering Blockchain and Smart contracts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lightrains.com" # the base hostname & protocol for your site
logo: assets/img/lightrains-logo.png

twitter_username: lightrainstech
github_username:  lightrainstech
gplus: https://plus.google.com/108900746872278115127
address: G3B, Thejaswini, Technopark Campus, Trivandrum, 695581
phone:  91 471 4000056

# Build settings
markdown: kramdown
permalink: :title

# Handling Reading
safe:         false
exclude:      [
  ".git",
  ".svn",
  "assets/semantic",
  "node_modules",
  "gulpfile.js",
  "semantic.json",
  "README.md",
  ".gulp-scss-cache",
  "assets/css/lightbox.min.css",
  "assets/css/main.css",
  "assets/css/main.scss",
  "assets/css/semantic.css",
  "assets/css/semantic.min.css",
  "assets/js/isotope.pkgd.js",
  "assets/js/jquery.min.js",
  "assets/js/lightbox.min.js",
  "assets/js/lightbox.min.map",
  "assets/js/semantic.js",
  "assets/js/site.js"
]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "/blogs/page:num/"
tag_page_dir: tag
tag_feed_dir: tag
tag_page_layout: tag_page
tag_feed_layout: tag_feed

social: [ "https://twitter.com/lightrainstech", "https://www.facebook.com/lightrainstechnolabs", "https://plus.google.com/108900746872278115127", "http://www.linkedin.com/company/1322794", "https://play.google.com/store/apps/developer?id=Lightrains+Technolabs+Pvt+Ltd", "https://foursquare.com/v/5281ebdd11d2f33611f594db", "https://www.youtube.com/channel/UC7FbfmuIVkfGeYW2u6H_IfQ", "http://www.acquia.com/partners/showcase/lightrains-technolabs-pvt-ltd", "https://github.com/lightrainstech"]

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: [local]
  blanklines: true
  profile: false
  startings: []
